controllers:
    resource: ../src/Controller/
    type: attribute

# replaced by PHP annotations:

# the "app_lucky_number" route name is not important yet
# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyController::number
